### ISSUE TITLE
Livemedia Stack

### ISSUE THREAD

**Issue by leandrodamascena** [cdk-patterns/serverless#120]
Hello, first of all, thank you very much for this incredible project.

I am building an infrastructure to deploy a Livemedia workflow for a customer. This workflow includes MediaPackage + MediaLive + S3 (a simple page with a player) and I'm writing using CDK + boto3, because MediaPackage is not available in CDK. Can I build this stack and open a PR here?

Thank you.

**Comment by nideveloper** [comment]
I will confess I have never used MediaPackage before but it sounds like a super interesting pattern that could help people out so absolutely please open a PR

**Comment by leandrodamascena** [comment]
Great to hear that @nideveloper! I've already deployed the infrastructure using console, but the customer wants to replicate it and now I'm writing the stack using CDK + Boto3. I'll read the Pattern section before open PR.

**Comment by leandrodamascena** [comment]
I changed a few things. To keep the stack more "standard cdk", I used "AwsCustomResource + AwsSdkCall" to avoid using boto3. I think it keeps the code and the code easier to maintain. I'm finishing the stack in Python then will open a PR and you can analyze the code and pattern before I rewrite in TS.
