### ISSUE TITLE
The Scheduled Lambda (Typescript)

### ISSUE THREAD

**Issue by rwsender** [cdk-patterns/serverless#134]
I want to work on a simple pattern demonstrating how to set up a lambda function to run on a schedule using EventBridge rules that writes data to DynamoDB on each run.

![The Simple Scheduled Lambda (1)](https://user-images.githubusercontent.com/9061301/101261344-825ba700-372e-11eb-9d54-4edcbf6bc38b.png)

**Comment by nideveloper** [comment]
This would be a very valuable pattern for others, I look forward to the contribution
