### ISSUE TITLE
S3ReactWebsite failed

### ISSUE THREAD

**Issue by frantzyy** [cdk-patterns/serverless#84]
I'm starting completely fresh here so I could have missed something in my setup.

I followed these steps: https://cdkworkshop.com/15-prerequisites/200-account.html

- using a personal AWS account
- using VS Code.

When running the s3-react-website cdk pattern I hit the following error:

`3ReactWebsite failed: Error: This stack uses assets, so the toolkit stack must be deployed to the environment (Run "cdk bootstrap aws://unknown-account/unknown-region")`

I then ran:

`cdk bootstrap aws://unknown-account/unknown-region`

Which resolved the issue but trying understanding how or why it didn't pick my AWS user profile that also has the region defined.

**Comment by cdk-patterns** [comment]
Do you have multiple aws profiles setup on your machine? I have seen that sometimes cause issues with the cdk cli

**Comment by frantzyy** [comment]
I do. I’ll try just using a single one. Thanks for the quick response.

**Comment by frantzyy** [comment]
Updating to a single profile work. 

I think I was missing the link between VS Code and my AWS CLI. So even though VS Code recognized the specific profile I wanted to use I needed to  `export AWS_PROFILE=user1` (https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html) so when running cdk commands it knew which profile I wanted.
