### ISSUE TITLE
rds proxy code doesn't work with mysql8

### ISSUE THREAD

**Issue by jonny-rimek** [cdk-patterns/serverless#92]
you have to update cdk in order to specify the mysql version

````js
    const rdsInstance = new rds.DatabaseInstance(this, 'DBInstance', {
      engine: rds.DatabaseInstanceEngine.mysql({
		  version: rds.MysqlEngineVersion.VER_5_7_30
	  }),
````

also the secret has changed to secrets andis now an array:

````js
    // Create an RDS Proxy
    const proxy = rdsInstance.addProxy(id+'-proxy', {
        secrets: [databaseCredentialsSecret],
        debugLogging: true,
        vpc,
        securityGroups: [dbConnectionGroup]
    });
````

also you need to specify the region in the bin/the-rds-proxy.ts
````js
new TheRdsProxyStack(app, 'TheRdsProxyStack',{
    env: {region: "us-east-1"}
});
````

**Comment by cdk-patterns** [comment]
Thanks, RDS Proxy was brand new when I created the pattern so I expect a few breaking changes will be introduced over the next few CDK versions. I will take a look today at updating with your suggestions, thanks for including code snippets

**Comment by cdk-patterns** [comment]
I updated and deployed both the Typescript and the Python version incorporating the first two changes. I deploy from cloud9 and don't need to manually specify a region in the setup. That's maybe something that needs better documented by the cdk team to say when/why you would do it manually vs coming in through aws profile

**Comment by jonny-rimek** [comment]
well the code assumes it is in us-east-1, my default region was eu-central-1 one and it didn't work until I specified the region.

https://github.com/cdk-patterns/serverless/blob/master/the-rds-proxy/typescript/lambda-fns/rds/rdsLambda.ts#L2

**Comment by cdk-patterns** [comment]
Oh ok, that's a different problem than what I was thinking. Yes, I should specify it deploys in us-east-1 then for now! Thanks

**Comment by jonny-rimek** [comment]
my plessure, thank you for the extrensive examples. extremely helpful
