### ISSUE TITLE
Auto Scaling Amazon MQ architecture

### ISSUE THREAD

**Issue by z8674558** [cdk-patterns/serverless#96]
I have been using CDK in my projects, and I would like to contribute this repo by adding [this pattern](https://aws.amazon.com/blogs/compute/creating-static-custom-domain-endpoints-with-amazon-mq/).

![architecture](https://d2908q01vomqb2.cloudfront.net/1b6453892473a467d07372d45eb05abc2031647a/2019/09/10/Solution-overview.png)

Thank you.

**Comment by cdk-patterns** [comment]
Awesome, it would be a great addition to the collection.
